### ISSUE TITLE
Pandas KeyError

### ISSUE THREAD

**Issue by spleonard1** [XiaofangJ/PhaseFinder#1]
Hi! Your recent paper is great! Phase variation is such a cool topic, glad it's getting some attention in host-associated communities. I'm excited to apply your PhaseFinder program on some genomes I have that aren't publicly available, but have run into a problem. I followed the installation instructions and took care of the dependencies, but I get this error when running the program on a Mac OSX 10.14.3:

| => python PhaseFinder.py ratio -i ./wkB2/wkB2.ID.fasta -1 ./wkB2/reads/wkB2_R1.fastq.paired.fq -2 ./wkB2/reads/wkB2_R2.fastq.paired.fq -p 16 -o ./wkB2/out
****** NOW RUNNING COMMAND ******: 
    bowtie -p 16  -a --best --strata ./wkB2/wkB2.ID.fasta -1 ./wkB2/reads/wkB2_R1.fastq.paired.fq -2 ./wkB2/reads/wkB2_R2.fastq.paired.fq -S|    samtools view -@ 16 -F 4 -h  |sam2bed -d|sortBed |cut -f 1-4,7 > ./wkB2/out.bed 
# reads processed: 26028097
# reads with at least one reported alignment: 155613 (0.60%)
# reads that failed to align: 25872484 (99.40%)
Reported 379312 paired-end alignments
##### Total time:  6.966 mins

****** NOW RUNNING COMMAND ******: 
    awk -v out=./wkB2/wkB2.ID.fasta.info.tab 'BEGIN{OFS="\t"}{print $1"_F",$2,$3,$4,$5"\n"$1"_R",$2,$3,$4,$5 > out".bed";print $1"_F", $6 "\n" $1"_R",$6 > out".info" }'  ./wkB2/wkB2.ID.fasta.info.tab
    awk '{print $1"\t"$2"\t"$3"\t1\n"$1"\t"$4"\t"$5"\t1\n"$1"\t"$2"\t"$5"\t-1"}' ./wkB2/wkB2.ID.fasta.info.tab.bed |slopBed -b 10 -g ./wkB2/wkB2.ID.fasta.info.tab.info |    sortBed|intersectBed -c -f 1 -a - -b ./wkB2/out.bed |awk '{a[$1]+=$4*$5}END{for(i in a){print i"\t"a[i]}}'|sort -k1,1|sed 's/_F\t/\tF\t/;s/_R\t/\tR\t/' >./wkB2/out.span.count
##### Total time:  .016 mins

****** NOW RUNNING COMMAND ******: 
    cat ./wkB2/out.bed|awk 'BEGIN{OFS="\t"}{print $4,$5,$1}'|sed 's/_\(.\)$/\t\1/g'|awk '{if(and(64,$2)){P=1}else{P=2};print $1"\t"P"\t"$3"\t"$4}' > ./wkB2/out.tab
    cut -f 1-3 ./wkB2/out.tab|sort|uniq -u|fgrep -f - ./wkB2/out.tab|cut -f 3-4|sort|uniq -c|awk '{print $2"\t"$3"\t"$1}' >./wkB2/out.pe.count 
fgrep: -: No such file or directory
##### Total time:  .333 mins

PhaseFinder.py:190: FutureWarning: read_table is deprecated, use read_csv instead.
  df = pd.read_table(infile, sep="\t", names=("ID", "dir", "count"))
Traceback (most recent call last):
  File "PhaseFinder.py", line 412, in <module>
    args.func(args)
  File "PhaseFinder.py", line 238, in pipeline_align
    "Pe_F": dfmerge["F_x"].astype(int),
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 2658, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'F_x'

I have python2.7 and pandas installed:

Package         Version
--------------- -------
biopython       1.73   
nose            1.3.7  
numpy           1.15.4 
pandas          0.24.1 
pip             18.0   
python-dateutil 2.8.0  
pytz            2018.9 
scipy           1.1.0  
setuptools      40.4.3 
six             1.12.0 
wheel           0.32.0 

Finally, why do you use bowtie instead of bowtie2? When I try mapping to the simulated inverted repeats with bowtie2 by hand, I get much higher mapping %. 

Thanks for your time!

**Comment by XiaofangJ** [comment]
Based on the error message "fgrep: -: No such file or directory", it seems that you have run PhaseFinder on Mac OS. Please try to run it on linux. or you can try to run the command line separately. 

The reason we chose bowtie rather than bowtie2 is because bowtie2 allow for gapped alignment, which is what we don't want, especially in the context of metagenomic read alignment.

**Comment by spleonard1** [comment]
Great! I fixed this a while back, I downloaded the gnu versions of sed /
awk etc using homebrew. it worked fine on my Mac after that. Thanks so much!

**Comment by spleonard1** [comment]
all fixed, I'm closing.
