### ISSUE TITLE
Discrepency in recommended filter for invertible regions

### ISSUE THREAD

**Issue by sconlan** [XiaofangJ/PhaseFinder#10]
There are slightly different recommendations for filtering in the paper supplement compared to the Github recommendations (> vs >=).

Github, "Our default is to classify a region as invertible if at least 1% 
of reads support the R orientation with a minimum Pe_R > 5 and Span_R > 3."

Supplemental, "For a region to be identified as invertible, we require at 
least five reads supporting the R orientation from the paired-end reporting 
method, and three reads supporting the R orientation from the spanning method. 
Furthermore, the number of reads supporting the R orientation must be at 
least 1% of the total reads that uniquely align to the F and R version of the
invertible DNA region."

**Comment by XiaofangJ** [comment]
The aim of PhaseFinder is to detect reliable invertible regions, and it is up to you to choose the threshold to balance the false positive and false negative rate.
