### ISSUE TITLE
Modifications for single-end data

### ISSUE THREAD

**Issue by alyssah7** [XiaofangJ/PhaseFinder#12]
Hello, 

I am trying to modify the source code for this tool locally to work with single-end sequencing data. Is this something I should be able to do? Or does the efficacy of the tool depend on information from paired-end reads? I am able to run it with my data without error, but the .ratio.txt output file is always outputting 0 for all columns in each of my 500 samples. 

Thanks!

**Comment by alyssah7** [comment]
Just following up on this -- I happen to have single end data and would like to use PhaseFinder. Is there any reason you'd recommend against using single end data?

**Comment by Chemokine1** [comment]
> Hello,
> 
> I am trying to modify the source code for this tool locally to work with single-end sequencing data. Is this something I should be able to do? Or does the efficacy of the tool depend on information from paired-end reads? I am able to run it with my data without error, but the .ratio.txt output file is always outputting 0 for all columns in each of my 500 samples.
> 
> Thanks!

I would like to know if you came up with this solution and if so, can you kindly share it?

**Comment by alyssah7** [comment]
> > Hello,
> > I am trying to modify the source code for this tool locally to work with single-end sequencing data. Is this something I should be able to do? Or does the efficacy of the tool depend on information from paired-end reads? I am able to run it with my data without error, but the .ratio.txt output file is always outputting 0 for all columns in each of my 500 samples.
> > Thanks!
> 
> I would like to know if you came up with this solution and if so, can you kindly share it?

**Comment by alyssah7** [comment]
@Chemokine1 Yes, I got it to work! I had made changes to the source code right before their last set of changes were pushed, so it looks like there were more changes than there actually were. Attaching here as a txt file bc it won't let me add as a .py. Also including the yaml file (also as .txt and without my conda prefix at the bottom) in case you run into version incompatibility issues. 

run with: 
python PhaseFinder_SE.py ratio -i /PATH/TO/REF -1 /PATH/TO/SINGLE/END/FQ -p 8 -o /OUTPUT/FILE/ROOT

Good luck -- hope it works for you!

[PhaseFinder_SE.txt](https://github.com/user-attachments/files/16130567/PhaseFinder_SE.txt)
[phasefinder_env_yaml_no_prefix.txt](https://github.com/user-attachments/files/16130596/phasefinder_env_yaml_no_prefix.txt)
