### ISSUE TITLE
It has SyntaxError: invalid syntax when i use the example files to test PhaseFinder

### ISSUE THREAD

**Issue by brLiSCG** [XiaofangJ/PhaseFinder#2]
Hi,
I try to use the example files to test PhaseFinder, and run the pipeline 

python PhaseFinder.py  -h

but it is failing, here is the output:

  File "PhaseFinder.py", line 82
    print run_cmd(cmd)
                ^
SyntaxError: invalid syntax

The same result happens when I use other commands
I am sure I have configured the prerequisites and their dependencies.
I do not understand why does "invalid syntax" appear. 
What is here wrong?
Thank you very much in advance!

**Comment by schmittel** [comment]
Same issue here. Was there a solution identified?
Many thanks

**Comment by metageni** [comment]
I had the same issue. I think it is because the pipeline was developed to run on Python 2.X. Try calling print as a function - with parameters - it may fix. 

I did not have the chance to test it because I'm missing some of the dependencies.

**Comment by YiyanYang0728** [comment]
> 
> 
> Hi,
> I try to use the example files to test PhaseFinder, and run the pipeline
> 
> python PhaseFinder.py -h
> 
> but it is failing, here is the output:
> 
> File "PhaseFinder.py", line 82
> print run_cmd(cmd)
> ^
> SyntaxError: invalid syntax
> 
> The same result happens when I use other commands
> I am sure I have configured the prerequisites and their dependencies.
> I do not understand why does "invalid syntax" appear.
> What is here wrong?
> Thank you very much in advance!

It is highly likely that this program is written in Python 2.x, but the python you use is Python 3.x. So there seems to be two ways to solve it.
1. The first is to replace all "print xxx" with "print(xxx)" in the program then it may work. But you may meet with other problems due to the differences btw Python 2 and Python 3.
2. The second is to install Ananconda3 firstly and then create a environment by typing:
======================
conda create -n py2 python=2.7
conda activate py2
======================
And run this program under this environments (remember to install all the dependencies for this env first).

**Comment by acvill** [comment]
> 2. The second is to install Ananconda3 firstly and then create a environment by typing in shell:
>    ======================
>    conda create -n py2 python=2.7
>    conda activate py2
>    ======================
>    And run this program under this environment (remember to install all the dependencies for this env first).

For anyone interested, I followed the suggestion by YiyanYang0728 and implemented PhaseFinder in a miniconda3 environment. First, I created the environment and installed the python dependencies. 

    source ${HOME}/miniconda3/bin/activate
    conda create --name PhaseFinder python=2.7
    conda activate PhaseFinder
    conda install biopython
    conda install pandas

Then, I downloaded and unzipped the PhaseFinder repository.

    wget https://github.com/XiaofangJ/PhaseFinder/archive/refs/heads/master.zip
    unzip master.zip
    mv PhaseFinder-master PhaseFinder

Before calling PhaseFinder, I add the external dependencies to my path. 

    export PATH=/programs/EMBOSS-6.6.0/bin:$PATH
    export PATH=/programs/bowtie2-2.3.0:$PATH
    export PATH=/programs/bedops-2.4.35/bin:$PATH
    export PATH=/programs/bedtools2-2.29.2/bin:$PATH
    python PhaseFinder.py -h
