### ISSUE TITLE
No reads mapping despite the fact that they were used to assemble the genome

### ISSUE THREAD

**Issue by bananabenana** [XiaofangJ/PhaseFinder#3]
Hi, software is working for first two steps, but when I use the ratio command I get no reads mapping. All dependencies are installed. 

To clarify, I use paired end reads to assemble a genome which was used in the `locate` and `create` commands. I then used the `ratio` command with those same paired end reads against the .fasta output of `create` and get no reads mapping.

reads with at least one reported alignment: 0 (0.00%)
reads that failed to align: 767218 (100.00%)

I don't see how this is possible, as I used these reads to assemble this genome. These reads have no issue mapping in other software.

Code used to run this (using python 2.7 env on ubuntu 18.04):
`python PhaseFinder.py ratio -i create.fasta -1 R1.fastq -2 R2.fastq -p 4 -o ratio_output`

Could you please tell me what I am doing wrong?

**Comment by seangibbons** [comment]
I've been playing with this script as well and noticed a couple of things. First, you probably saw that it was written in Python 2.7, so I used anaconda to create a python 2 environment and then used conda and pip to install all the dependencies from within that environment (i.e. using versions of packages compatible with python 2). Second, it looks like the awk commands are breaking -- probably some kind of versioning issue? Anyway, if I replace 'awk' with 'gawk' in the PhaseFinder.py script, then everything runs fine (at least with the tutorial data -- I haven't tried running on real data yet).

**Comment by bananabenana** [comment]
> First, you probably saw that it was written in Python 2.7, so I used anaconda to create a python 2 environment and then used conda and pip to install all the dependencies from within that environment (i.e. using versions of packages compatible with python 2). Second, it looks like the awk commands are breaking -- probably some kind of versioning issue? Anyway, if I replace 'awk' with 'gawk' in the PhaseFinder.py script, then everything runs fine (at least with the tutorial data -- I haven't tried running on real data yet).

Hi Sean, thanks for the repsonse and sorry for the late reply! I did what you mentioned, replacing 'awk' with 'gawk' in the script, however still 0% of reads mapped. I was already using a py2 env as well with dependencies installed.

Do you have any other ideas? Given this is just measure of essentially forward and reverse read mapping, I wonder if I could just use any other mapping tool and then just do auto counting for forward and reverse reads?

**Comment by schmittel** [comment]
Having the same issue here - consistently no reads mapping.

**Comment by seangibbons** [comment]
I'm guessing that the no read mapping is a real result...the script is using bowtie, which is a pretty reliable mapper. I believe the pipeline only tries to map reads to inverton regions (and flanking sequences) -- i.e. it's not mapping reads to the entire reference. Do you see any inverton regions in your reference?

**Comment by bananabenana** [comment]
Thanks for your response Sean.
Yes I understand what you mean, I have had previous success with bowtie in other projects. I was only mapping reads to the created fasta file which contains the invertron regions. In the intertron file, there are a total of 1522 contigs produced, half being F and the other half R.
It seems unlikely to have no reads hitting 1522 sequences, all >2kb in length, when using 300 bp reads.
But maybe you're right and this is just the result - that there is no invertrons within the genome.

**Comment by alexcrofts** [comment]
I am having a similar issue.  I built a genome from paired end reads, found IR regions and had a successful step 2, and had no reads map in step 3.  Using Py2.7 with correct dependencies in Ubunutu 20. Running the test data works fine for me (without changing any code). 

I understand that I may not have invertible regions (no mix of forward and reverse reads at any IR regions found in steps 1/2) but there should still be reads that map in 100% of aeither F or R orientation in step 3 for each one, right?

**Comment by Owuorgpo** [comment]
I suspect it cannot process compressed .gz  fastq files. Try uncompress and see if it maps @alexcrofts. Seem like something worth correcting as large projects aren't likely.
