### ISSUE TITLE
How to use -m and -r arguments when calling locate

### ISSUE THREAD

**Issue by acvill** [XiaofangJ/PhaseFinder#6]
Thank you for writing and maintaining PhaseFinder!

PhaseFinder locate includes optional arguments `-m`/`--mismatch` and `-r`/`--IRsize`. The help file specifies that these options are "used with -einv", but I cannot figure out the proper syntax.

A worked example with the test data...

---

    python PhaseFinder.py locate -f data/test.fa -t data/out.tab -g 15 85 -p

This returns a tab-delimited output with 31 inverted repeats. Visual inspection of the inverted repeats shows that there are some mismatches between paired repeats, as expected given the default of 3 allowed mismatches. 

---

    python PhaseFinder.py locate -f data/test.fa -t data/out.tab -g 15 85 -p -e -m 0 -r 50
    python PhaseFinder.py locate -f data/test.fa -t data/out.tab -g 15 85 -p -e "-m 0 -r 50"

Both of these commands return an error -- `PhaseFinder.py locate: error: argument -e/--einv: expected one argument`.  The same is true when using the long versions of all options. 

---

    python PhaseFinder.py locate -f data/test.fa -t data/out.tab -g 15 85 -p -m 0 -r 50

Including `-m` and `-r` without calling `-e` yields an output file with the same 31 results, some of which are imperfect IR pairs. Of course, I am expecting only perfect IR pairs with `-m 0`. 

---

    python PhaseFinder.py locate -f data/test.fa -t data/outg.tab -g 15 85 -e ""
    python PhaseFinder.py locate -f data/test.fa -t data/outg.tab -g 15 85 --einv ""

Both of these commands prompt me to specify, one at a time, the penalties for gaps and mismatches in einverted, though this does not include an option to specify a mismatch cutoff, only a mismatch penalty.   

---

Can you please update the README to include an example of a PhaseFinder locate command that includes `-m` and `-r` with the proper syntax?

**Comment by XiaofangJ** [comment]
One way to work around it is by adding space between "-gap" and the first quotation mark. 

```
python PhaseFinder.py locate -f data/test.fa -t data/out.tab  -m 0 -r 50  -e " -gap 100 -threshold 51 -match 5 -mismatch -9"

```

or  using add `=`

```
 python PhaseFinder.py locate -f data/test.fa -t data/out.tab  -m 0 -r 50  -e="-gap 100 -threshold 51 -match 5 -mismatch -9" 
```

for inverted to run, all these four parameters "gap/threshold/match/mismatch" are required.

**Comment by acvill** [comment]
Thanks for the clarification!
