### ISSUE TITLE
Werid output，The PE_F and Span_F =0 ,  But the PE_R and Span_R =6

### ISSUE THREAD

**Issue by actledge** [XiaofangJ/PhaseFinder#7]
As the title says, 
one of the results I got was this:
13G412_Scaf7:6598-6611-6716-6729	0	6	1.0	0	6	1.0

So I don't know Why is there no reads match in the forward direction

I assembled the genome using Spades,
and use following command of phasefinder
PhaseFinder.py locate -f /data1/act/13G412.fa  -t ./tmp/13G412.einverted.tab -g 15 85 -p 
PhaseFinder.py create -f /data1/act/13G412.fa -t ./tmp/13G412.einverted.tab -s 1000 -i ./tmp/13G412.ID.fasta
PhaseFinder.py ratio -i ./tmp/13G412.ID.fasta -1 /data1/act/s_G412_1.clean.fq.gz -2 /data1/act/SP/s_G412_2.clean.fq.gz -p 16 -o ./result/13G412.out

**Comment by XiaofangJ** [comment]
Can you share the scaffold "13G412_Scaf7" sequences with me?

**Comment by actledge** [comment]
Yes, the attachment is the sequence of 13G412_Scaf7.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XiaofangJ/PhaseFinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月19日(星期四) 晚上9:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XiaofangJ/PhaseFinder] Werid output，The PE_F and Span_F =0 ,  But the PE_R and Span_R =6 (#7)





 
Can you share the scaffold "13G412_Scaf7" sequences with me?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XiaofangJ** [comment]
> Yes, the attachment is the sequence of 13G412_Scaf7.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "XiaofangJ/PhaseFinder" ***@***.***&gt;; 发送时间:&nbsp;2021年8月19日(星期四) 晚上9:15 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [XiaofangJ/PhaseFinder] Werid output，The PE_F and Span_F =0 , But the PE_R and Span_R =6 (#7) Can you share the scaffold "13G412_Scaf7" sequences with me? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

No attachement was sent.

**Comment by actledge** [comment]
> > Yes, the attachment is the sequence of 13G412_Scaf7.
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "XiaofangJ/PhaseFinder" _**@**_._**>; 发送时间: 2021年8月19日(星期四) 晚上9:15 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [XiaofangJ/PhaseFinder] Werid output，The PE_F and Span_F =0 , But the PE_R and Span_R =6 (#7) Can you share the scaffold "13G412_Scaf7" sequences with me? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> 
> No attachement was sent.

oh...maybe Github's reply does not support attachments, I don't know much about it.
So I directly send it to your email this time.
