### ISSUE TITLE
flanksize explained

### ISSUE THREAD

**Issue by mmpust** [XiaofangJ/PhaseFinder#9]
Hi, this is a great tool!

Can you explain a bit more about the -s or flanksize parameter? 
```
usage: PhaseFinder.py create [-h] -f  -t  -s  -i

optional arguments:
  -h, --help         show this help message and exit
  -f , --fasta       input genome sequence file in fasta format
  -t , --tab         table with inverted repeat coordinates
  -s , --flanksize   base pairs of flanking DNA on both sides of the
                     identified inverted repeats
  -i , --inv         output path of the inverted fasta file
```
 What exactly does this mean and what is an appropriate window of sizes to be used?
 Thanks!

**Comment by XiaofangJ** [comment]
This depends on the read length and insertion size of your FASTQ file. I would recommend it to be longer than read_length*2 + insertion size
